package gpms.policy;

public enum ProposalStage {
	
	PROPOSAL_NOT_READY_TO_SUBMIT,
	PROPOSAL_READY_TO_SUBMIT,
	PROPOSAL_SUBMITED_TO_CHAIR,
	PROPOSAL_SUBMITED_TO_DEAN,
	PROPOSAL_APPROVED_BY_DEAN;

}
